# Configuración de Infraestructura como Código para Despliegue en la Nube (Render.com)
services:
  - type: web
    name: control-parental-server
    env: docker # Utilizar el Dockerfile para máxima compatibilidad
    plan: free # Plan gratuito
    region: oregon # Región del servidor
    envVars:
      - key: PORT
        value: 6000
      - key: NODE_ENV
        value: production
      - key: PERSISTENT_DIR
        value: /usr/src/app/data # Ubicación local en el contenedor para la base de datos
